sudo: require
dist: trusty
language: node_js
node_js: "5.3"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
      - node_modules
install:
      - travis_retry npm install
      - npm install -g coveralls@2.11.3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - wct --local=chrome
after_success: "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
